config/routes.rb
CheffGb::Application.routes.draw do
  get "static_pages/home"

  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :email, :nome, :receita
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])
	@homepage = static_pages_home_path

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Receita enviada com sucesso!' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crie o Pr??o GB</title>
  <%= stylesheet_link_tag "custom", :media => "all"  %>
  <%= javascript_include_tag "bootstrap" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-narrow">

      <div class="masthead">
       <div id="logo"></div>
       <%= yield %>
	   
      </div>
      <div class="footer">
        <p>Planejamento, Criação e Execução
       </p>
      <%= link_to image_tag("studioslogo.png", alt: "StudiosMedia"), 'http://#' %> &nbsp; &nbsp; &nbsp; &nbsp;<%= link_to image_tag("sgslogo.png", alt: "StudiosMedia"), 'http://#' %></div>

    </div> <!-- /container -->


</body>
</html>




    

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

		<div id="formulario">
		<form class="form-horizontal">
 <div class="control-group">
  <div class="controls">
    <%= f.text_field :nome, :placeholder => "Insira seu Nome" %>
  </div>
    </div>
 <div class="control-group">
  <div class="controls">
    <%= f.text_field :email, :placeholder => "Insira seu e-mail" %>
  </div>
    </div>
<div class="control-group">
    <div class="controls">
    <%= f.text_area :receita, :placeholder => "Descreva aqui como seria seu GB perfeito" %>
</div>
    </div>
 <div class="control-group">
    <div class="controls">
    <%= f.submit "Enviar", :class => 'btn btn-large btn-primary' %>
    </div>
  </div>
  </form>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div id="howto">
<div id="txt">
<h1>Listagem de Receitas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Receita</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.nome %></td>
    <td><%= recipe.email %></td>
    <td><%= recipe.receita %></td>
    <td><%= link_to 'Exibir', recipe %></td>
    <td><%= link_to 'Editar', edit_recipe_path(recipe) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

</div>
</div>

app/views/recipes/new.html.erb
  <div class="jumbotron">
        <h3>Criar Receita</h3>

<%= render 'form' %>

<%= link_to 'Voltar', static_pages_home_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

        <div id="howto">
        <div id="txt">
<p>
  <b>Nome:</b>
  <%= @recipe.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @recipe.email %>
</p>

<p>
  <b>Receita:</b>
  <%= @recipe.receita %>
</p>
</div>
</div>
<%= link_to 'Editar', edit_recipe_path(@recipe) , :class =>"btn btn-large btn-success"  %>
<%= link_to 'Voltar', static_pages_home_path , :class =>"btn btn-large btn-success"  %>

app/views/static_pages/home.html.erb
 <div class="jumbotron">
        <h3>Crie o próximo sanduíche do GB e ganhe dinheiro por cada unidade vendida!</h3>
        <div id="howto">
        <div id="txt">
        <h4>Como funciona</h4>
      <h5> Você envia sua receita e no final do período de 30 dias o nosso <strong>Original Gran Cheff GB </strong> escolhe as 3 melhores. É aberta então a votação para o público escolher a preferida entre as 3 finalistas. A receita com mais votos entra no cardápio por 1 mês e o criador recebe <em>royalties</em> de R$ 0,50 por cada unidade vendida. <strong> Fácil não ?! </strong></h5>
      </div>
</p></div>
<%= link_to 'Enviar Receita', new_recipe_path , :class =>"btn btn-large btn-success"  %>

      </div>